### ISSUE TITLE
When adding 

### ISSUE THREAD

**Issue by weiyeh** [sbt/sbt-digest#13]
When following these instructions in the README, 
> Your project's build file also needs to enable sbt-web plugins. For example with build.sbt:
> lazy val root = (project. in file(".")).enablePlugins(SbtWeb)

I get this error when I try to run the modified build.sbt file:

> build.sbt:29: error: missing arguments for method in in trait Project;
> follow this method with `_' if you want to treat it as a partially applied function
> lazy val root = (project. in file(".")).enablePlugins(SbtWeb)
>__________________ ^
> sbt.compiler.EvalException: Type error in expression
>        at sbt.compiler.Eval.checkError(Eval.scala:384)

**Comment by huntc** [comment]
This feels like you have an older version of sbt declared in built.properties. Try 0.13.6.

**Comment by pvlugter** [comment]
That's a mistake in the readme, which I've updated.

Remove the extra dot after "project":
```scala
lazy val root = (project in file(".")).enablePlugins(SbtWeb)
```

Also, if you're using Play you don't need to enable SbtWeb as it's automatically enabled for you.
