### ISSUE TITLE
SASS/SCSS bootstrap/font-awesome and sbt-digest

### ISSUE THREAD

**Issue by schmitch** [sbt/sbt-digest#17]
Hello, currently when using sbt-sass with sbt-digest it won't use the digested files since you would need to specify your font path inside the scss file:

```
$icon-font-path: "/assets/lib/bootstrap-sass/assets/fonts/bootstrap";
$fa-font-path: "/assets/lib/font-awesome/fonts";
```

And then the library will add the correct font file to this url.
So we have no control over it, is there any way to support that?

**Comment by eximius313** [comment]
+1

**Comment by jroper** [comment]
I think you're looking for this plugin:

https://github.com/neomaclin/sbt-simple-url-update
