### ISSUE TITLE
Way to filter out original files from build?

### ISSUE THREAD

**Issue by adamrabung** [sbt/sbt-digest#18]
Is there a way to remove the original asset from a build once sbt-digest has created a copy with the hash in the name? For example, with original asset:
/public/images/puppy.jpeg
sbt-digest creates:
/public/images/2b1c84d0dbfa6512f08aada345c6958c-puppy.jpeg
and then 'activator dist' includes both of them in the assets jar. This effectively doubles the size of the jar. Is there a way to prevent this, using sbt-digest or general sbt?
Thank you,
Ada,

**Comment by 0xbaadf00d** [comment]
I have used sbt-filter (com.slidingautonomy.sbt" % "sbt-filter" % "1.0.1") to do this; but sbt-diggest is so bugged. If the original file does not exist on the "assets" JAR; the diggested version will never appear (get a 404).  

In fact, sbt-diggest is useless except if you want an assets JAR size multiplicated by 2.

**Comment by eximius313** [comment]
have you found other solution for this problem?

**Comment by 0xbaadf00d** [comment]
@eximius313 nop, I have just disabled this plugin.

**Comment by jroper** [comment]
Filtering out the original assets should be done using `sbt-filter`. The thing that is causing the 404's when you do that is not sbt-digest (how can it, it's an sbt plugin not a webserver) but presumably is Play Framework. If you want that behaviour changed you'll have to raise an issue on Play saying that digested assets with no undigested asset equivalent should still be served.

**Comment by eximius313** [comment]
@jroper I believe that this issue is different than [this one](https://github.com/sbt/sbt-digest/issues/20#issuecomment-324311545)
