### ISSUE TITLE
Redirect to new version of file?

### ISSUE THREAD

**Issue by eximius313** [sbt/sbt-digest#20]
I have and an image ```sample.png``` which is processed by ```sbt-digest``` so it's served from both urls:
```/assets/images/sample.png```
and
```/assets/images/f563fc66172fc3e21a0370e3d17ad556-sample.png```

When I then redeploy the server, I observe that all requests to already cached (by Facebook for example) image, got 404 status (which is bad, since we still have valid image):
```404 -> /assets/images/f563fc66172fc3e21a0370e3d17ad556-sample.png: Resource not found by Assets controller```

Shouldn't it return 301 and point to the new file instead?

**Comment by jroper** [comment]
This is a Play issue, doesn't really have anything to do with `sbt-digest`, all `sbt-digest` does is digest files. If you feel Play should send redirects in this situation, then raise the discussion there.

**Comment by eximius313** [comment]
done
