### ISSUE TITLE
Mappings start with / which breaks things

### ISSUE THREAD

**Issue by nafg** [sbt/sbt-digest#21]
e.g. with a packagePrefix that ends with a "/", the jar entry has // in it and getResource doesn't work

**Comment by mdedetrich** [comment]
I have just come across this, and it took an entire day to try and find the cause of the problem, reproduction is here

https://github.com/mdedetrich/akka-http-with-scalajs-digest-issue

This is completely un-intuitive behaviour and I actually wasted a day trying to figure out what was going on

**Comment by mdedetrich** [comment]
@nafg @jroper I have fixed the issue in https://github.com/sbt/sbt-digest/pull/29. An explanation is in the PR.
