### ISSUE TITLE
Digested assets not retrieved in prod mode

### ISSUE THREAD

**Issue by abiacco** [sbt/sbt-digest#22]
I'm trying to enable digested assets to my play project.
I'm using play 2.5.10/2.5.12 and sbt-digest 1.1.1.
My assets are in the app/assets subdirectory

Configuration in build.sbt for dev is:
pipelineStages in Assets := Seq(digest)
Configuration in build.sbt for prod is:
pipelineStages := Seq(digest)

Both modes are using the Versioned calls, so in routes I have:
GET     /assets/*file               controllers.Assets.versioned(path="/public", file: Asset)
And in my view files something like:
        <link rel="stylesheet" type="text/css" media="screen" href="@routes.Assets.versioned("stylesheets/login.css")">

For dev, i'm just running "activator run"
For prod, I'm packaging with sbt and universal:packageZipTarball (also tried activator with universal)

My assets get digested ok in both dev/prod mode. In prod mode i find them in an externalized jar.

When i run the app in dev mode, it works fine. Digested assets are served.
When i run the app in prod mode, the non-digested assets are served.

For the life of me, I can't figure out why they don't work in prod mode.
To test whether i'm in dev or prod mode i'm checking play.api.Play.isProd
I've read numerous docs and guides on this and still have come up short.
I've tested in both windows and linux with similar results.

Any guidance would be appreciated. Wondering if i should also post this in the Play google group as well?

Thanks!

**Comment by abiacco** [comment]
anybody? still haven't figured this out

**Comment by jroper** [comment]
This is just the plugin for digesting assets, Play is what's responsible for actually locating digested assets and serving them.
