### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by nielsbuwen** [sbt/sbt-digest#35]
Hi,

are there any plans to support Scala 3? Currently the releases seem to be build for Scala 2 only

**Comment by mkurz** [comment]
sbt-digest is a sbt plugin, sbt plugins are build with Scala 2.12. sbt plugins simple do not work with Scala 3, also not with Scala 2.13. That's just how it works.
I think sbt 2.0 might change to Scala 3 but not sure.
So this is not a issue.
